name: Deploy to Firebase

on:
  push:
    branches:
      - main  # Deploy on pushes to the 'main' branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Adjust if needed

      - name: Install dependencies
        run: npm install

      - name: Build the React app
        run: npm run build

      - name: Login to Firebase
        run: |
          npm install -g firebase-tools 
          firebase login:ci

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting
